version: '3.8'

name: access-control-app

networks:
  access-control-app-network:
    driver: bridge

services:
  postgres:
    image: postgres:16.2
    container_name: access-control-app-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: access_control_db
    ports:
      - 5432:5432
    networks:
      - access-control-app-network

  pgadmin:
    container_name: access-control-app-pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@store.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - 8080:80
    networks:
      - access-control-app-network