
name: Api Deployment

on:
  push:
    branches:
      - feat/deploy

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.0'

    - name: Build
      run: cd api && go build -o myapi

    - name: Upload Go binary
      env:
        SSH_HOST: ${{ secrets.SSH_HOST  }}
        SSH_USERNAME: ${{ secrets.SSH_USERNAME  }}
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY  }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa.pem
        chmod 600 ~/.ssh/id_rsa.pem
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa.pem $SSH_USERNAME@$SSH_HOST echo "SSH connection successful"
      
    - name: Cleanup SSH Key
      if: always()
      run: |
        rm -f ~/.ssh/id_rsa.pem
        
