name: Deploy API

on:
  push:
    branches:
      - dev

jobs:

  build:
    if: startsWith(github.event.head_commit.message, 'deploy(api):')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.0'

    - name: Build
      run: cd api && go build -o myapi

    - name: Upload to Server and Restart Service
      if: ${{ success() }}
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SSH_HOST: ${{ secrets.SSH_HOST }}
        SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa.pem
        chmod 600 ~/.ssh/id_rsa.pem
        scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa.pem api/myapi $SSH_USERNAME@$SSH_HOST:/tmp/myapi
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa.pem $SSH_USERNAME@$SSH_HOST 'sudo mv /tmp/myapi /usr/local/bin/myapi && sudo systemctl restart myapi.service'
      
    - name: Cleanup SSH Key
      if: always()
      run: |
        rm -f ~/.ssh/id_rsa.pem
